name: Update Stream Calendar

on:
  schedule:
  - cron: '0 15 * * *' #Runs daily at 15:00 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run calendar bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          MESSAGE_ID: ${{ secrets.MESSAGE_ID }}
          ROLE_ID: ${{ secrets.ROLE_ID }}
          PING_ROLE: ${{ secrets.PING_ROLE }}
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
          TWITCH_BROADCASTER_ID: ${{ secrets.TWITCH_BROADCASTER_ID }}
          EMBED_COLOR: ${{ secrets.EMBED_COLOR }}
          TIMEZONE: ${{ secrets.TIMEZONE }}
        run: python src/main.py